# Generated by Django 2.2.2 on 2019-10-22 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationshipstatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genderinterest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='user_requested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='user_requesting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_requesting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followinglist',
            name='user_followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followinglist',
            name='user_following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
